import {Comment} from './Comment'

export const COMMENT: Comment[] = [
    {
        id: 1,
        name: 'Ricma',
        messages: 231,
        membership: '1. 12. 2021',
        date: 'Today',
        time: '6:42',
        imageOP:'assets/img/user.png',
        text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc faucibus, sapien eu convallis volutpat, justo metus mollis ex, sit amet auctor dolor odio nec enim. Proin vitae massa porttitor, congue justo vitae, blandit odio. Donec venenatis turpis ligula, at ornare magna imperdiet ut. Aliquam erat volutpat. Vivamus at sem lacus. Nam dui nunc, semper non imperdiet sed, tristique ut nulla. Duis vitae diam ornare nulla laoreet rutrum ac quis urna. Ut aliquet eros eu fermentum ultricies. Nullam sed elementum tortor. Morbi quis pulvinar nulla. Nullam ut gravida ipsum. Donec convallis iaculis erat, eu viverra mi mattis non.',
    },
    {
        id: 2,
        name: 'Somila',
        messages: 29,
        membership: '9. 2. 2022',
        date: 'Today',
        time: '8:01',
        imageOP:'assets/img/user.png',
        image:'assets/img/forumtitle.png',
        text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc faucibus, sapien eu convallis volutpat, justo metus mollis ex, sit amet auctor dolor odio nec enim. Proin vitae massa porttitor, congue justo vitae, blandit odio. Donec venenatis turpis ligula, at ornare magna imperdiet ut. Aliquam erat volutpat. Vivamus at sem lacus. Nam dui nunc, semper non imperdiet sed, tristique ut nulla. Duis vitae diam ornare nulla laoreet rutrum ac quis urna. Ut aliquet eros eu fermentum ultricies. Nullam sed elementum tortor. Morbi quis pulvinar nulla. Nullam ut gravida ipsum. Donec convallis iaculis erat, eu viverra mi mattis non.        Curabitur quis consequat odio, vel convallis ante. Quisque pellentesque ipsum elit, non bibendum lacus finibus nec. Aenean vestibulum consequat neque id efficitur. Suspendisse potenti. Nullam vehicula neque et ex dignissim malesuada. Integer at velit in arcu rhoncus rutrum in convallis est. Vestibulum sodales mattis dolor, placerat tristique felis condimentum in. Praesent vitae metus orci. Proin maximus accumsan diam, eu fringilla justo interdum at.',
    },
    {
        id: 3,
        name: 'Somila',
        messages: 29,
        membership: '9. 2. 2022',
        date: 'Today',
        time: '8:01',
        imageOP:'assets/img/user.png',
        image:'assets/img/forumtitle.png',
        text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc faucibus, sapien eu convallis volutpat, justo metus mollis ex, sit amet auctor dolor odio nec enim. Proin vitae massa porttitor, congue justo vitae, blandit odio. Donec venenatis turpis ligula, at ornare magna imperdiet ut. Aliquam erat volutpat. Vivamus at sem lacus. Nam dui nunc, semper non imperdiet sed, tristique ut nulla. Duis vitae diam ornare nulla laoreet rutrum ac quis urna. Ut aliquet eros eu fermentum ultricies. Nullam sed elementum tortor. Morbi quis pulvinar nulla. Nullam ut gravida ipsum. Donec convallis iaculis erat, eu viverra mi mattis non.        Curabitur quis consequat odio, vel convallis ante. Quisque pellentesque ipsum elit, non bibendum lacus finibus nec. Aenean vestibulum consequat neque id efficitur. Suspendisse potenti. Nullam vehicula neque et ex dignissim malesuada. Integer at velit in arcu rhoncus rutrum in convallis est. Vestibulum sodales mattis dolor, placerat tristique felis condimentum in. Praesent vitae metus orci. Proin maximus accumsan diam, eu fringilla justo interdum at.',
    },
    {
        id: 4,
        name: 'Somila',
        messages: 29,
        membership: '9. 2. 2022',
        date: 'Today',
        time: '8:01',
        imageOP:'assets/img/user.png',
        image:'assets/img/forumtitle.png',
        text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc faucibus, sapien eu convallis volutpat, justo metus mollis ex, sit amet auctor dolor odio nec enim. Proin vitae massa porttitor, congue justo vitae, blandit odio. Donec venenatis turpis ligula, at ornare magna imperdiet ut. Aliquam erat volutpat. Vivamus at sem lacus. Nam dui nunc, semper non imperdiet sed, tristique ut nulla. Duis vitae diam ornare nulla laoreet rutrum ac quis urna. Ut aliquet eros eu fermentum ultricies. Nullam sed elementum tortor. Morbi quis pulvinar nulla. Nullam ut gravida ipsum. Donec convallis iaculis erat, eu viverra mi mattis non.        Curabitur quis consequat odio, vel convallis ante. Quisque pellentesque ipsum elit, non bibendum lacus finibus nec. Aenean vestibulum consequat neque id efficitur. Suspendisse potenti. Nullam vehicula neque et ex dignissim malesuada. Integer at velit in arcu rhoncus rutrum in convallis est. Vestibulum sodales mattis dolor, placerat tristique felis condimentum in. Praesent vitae metus orci. Proin maximus accumsan diam, eu fringilla justo interdum at.',
    },
];